### ISSUE TITLE
JSON Parsing error, unexpected character

### ISSUE THREAD

**Issue by Brin-o** [deflinhec/GodotGoogleSheet#8]
Hey,

I downloaded the demo you are providing and tried to setup a simple scene. However, regardless of what I do I seem to hit this error in the end:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/49071768/151579778-351a83c1-dd48-4c6f-aed9-1b9d84b1b88e.png">

This is the spreadsheet I'm using: https://docs.google.com/spreadsheets/d/1qveulE_T6uRvJTwxbBEN3ld_IpmXW8eAqqmf1maWeyE/edit?usp=sharing

**Comment by deflinhec** [comment]
The Google Sheets API v3 was turned down on August 2, 2021, and I've recently upgrade to Google Sheets API v4. Please confirm if this issue still exists.
